import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getStore, saveStore, initializeRepository, recordPaymentEvent, supabaseEnabled, closeRepository, getSupabaseUser } from './supabase-store.js';
import type { Product, Order } from './db.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const port = Number(process.env.PORT || 8787);
const isProduction = process.env.NODE_ENV === 'production';
const demoMode = !isProduction && process.env.DEMO_MODE !== 'false';
const adminPassword = process.env.ADMIN_PASSWORD || '';
const tokenSecret = process.env.SESSION_SECRET || (isProduction ? '' : 'local-demo-session-secret-change-me');
if (isProduction && (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY)) console.warn('Production warning: set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.');
if (isProduction && (!adminPassword || tokenSecret.length < 32)) console.warn('Production warning: set ADMIN_PASSWORD and a SESSION_SECRET of at least 32 characters.');

type AuthedRequest = express.Request & { admin?: { username: string } };
type OrderInput = Order & { items?: { productId: string; quantity: number }[] };

const now = () => new Date().toISOString();
const safeEqual = (a: string, b: string) => { const left = Buffer.from(a); const right = Buffer.from(b); return left.length === right.length && crypto.timingSafeEqual(left, right); };
const signSession = (username: string) => { const payload = Buffer.from(JSON.stringify({ username, exp: Date.now() + 1000 * 60 * 60 * 8 })).toString('base64url'); const signature = crypto.createHmac('sha256', tokenSecret).update(payload).digest('base64url'); return `${payload}.${signature}`; };
const verifySession = (token?: string) => { if (!token || !tokenSecret) return null; const [payload, signature] = token.split('.'); const expected = payload ? crypto.createHmac('sha256', tokenSecret).update(payload).digest('base64url') : ''; if (!payload || !safeEqual(signature || '', expected)) return null; try { const parsed = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')); return parsed.exp > Date.now() ? parsed : null; } catch { return null; } };
const rateFor = (city: string) => ({ Lagos: 8500, Abuja: 12000, 'Port Harcourt': 18000, Ibadan: 12000, Other: 18000 } as Record<string, number>)[city] || 18000;
const statusToDb: Record<string, string> = { 'Awaiting payment': 'awaiting_payment', 'Awaiting confirmation': 'awaiting_confirmation', 'Ready to ship': 'ready_to_ship', Shipped: 'shipped', 'Out for delivery': 'out_for_delivery', Delivered: 'delivered', Returned: 'returned', Cancelled: 'cancelled' };
const paymentToDb: Record<string, string> = { Pending: 'pending', Paid: 'paid', Failed: 'failed', Refunded: 'refunded', COD: 'cod' };
const assertProduct = (value: Partial<Product>) => !value.id || !value.name || !Number.isFinite(Number(value.price)) || Number(value.price) < 0 || !Number.isFinite(Number(value.stock)) || Number(value.stock) < 0 ? 'Product requires id, name, non-negative price, and non-negative stock.' : null;
const asyncRoute = (handler: express.RequestHandler): express.RequestHandler => (request, response, next) => Promise.resolve(handler(request, response, next)).catch(next);

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: process.env.PUBLIC_ORIGIN || true, credentials: Boolean(process.env.PUBLIC_ORIGIN) }));
app.use(express.json({ limit: '100kb', verify: (request, _response, buffer) => { (request as AuthedRequest & { rawBody?: Buffer }).rawBody = Buffer.from(buffer); } }));
app.use(rateLimit({ windowMs: 60 * 1000, limit: 240, standardHeaders: 'draft-8', legacyHeaders: false }));
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false });

function requireAdmin(request: AuthedRequest, response: express.Response, next: express.NextFunction) { if (demoMode && !adminPassword) { request.admin = { username: 'demo-admin' }; return next(); } const bearer = request.headers.authorization?.replace(/^Bearer\s+/i, ''); if (process.env.SUPABASE_AUTH_REQUIRED === 'true' && supabaseEnabled) { getSupabaseUser(bearer).then((user) => { if (!user) return response.status(401).json({ error: 'Supabase Auth session required.' }); request.admin = { username: user.email || user.id }; return next(); }).catch(() => response.status(401).json({ error: 'Supabase Auth session could not be verified.' })); return; } const session = verifySession(bearer); if (!session) return response.status(401).json({ error: 'Admin authentication required.' }); request.admin = { username: session.username }; return next(); }
function productResponse(product: Product) { return product; }

app.get('/api/health', (_request, response) => response.json({ ok: true, service: 'laptop-gadgets-commerce-api', database: supabaseEnabled ? 'supabase' : 'sqlite-demo', environment: isProduction ? 'production' : 'development' }));
app.post('/api/auth/login', loginLimiter, (request, response) => { const username = String(request.body?.username || ''); const password = String(request.body?.password || ''); if (demoMode && !adminPassword && username === 'demo' && password === 'demo') return response.json({ token: signSession('demo-admin'), user: { username: 'demo-admin', role: 'owner' }, demo: true }); if (username !== (process.env.ADMIN_USERNAME || 'admin') || !safeEqual(password, adminPassword)) return response.status(401).json({ error: 'Invalid admin credentials.' }); return response.json({ token: signSession(username), user: { username, role: 'owner' }, demo: false }); });
app.get('/api/auth/me', requireAdmin, (request: AuthedRequest, response) => response.json({ user: request.admin, demo: demoMode && !adminPassword }));

app.get('/api/reviews', asyncRoute(async (request, response) => { const store = await getStore(); const productId = String(request.query.productId || ''); return response.json(store.reviews.filter((review) => review.status === 'Published' && (!productId || review.productId === productId))); }));
app.post('/api/reviews', asyncRoute(async (request, response) => { const { productId, productName, customer, rating, comment } = request.body || {}; if (!productId || !productName || !customer || !comment || !Number.isInteger(Number(rating)) || Number(rating) < 1 || Number(rating) > 5) return response.status(400).json({ error: 'Product, customer, rating, and review text are required.' }); const store = await getStore(); const review = { id: `review_${Date.now()}`, productId, productName, customer, rating: Number(rating), comment, status: 'Pending' as const, createdAt: now() }; store.reviews = [review, ...store.reviews]; await saveStore(store); return response.status(201).json(review); }));
app.patch('/api/reviews/:id', requireAdmin, asyncRoute(async (request, response) => { const store = await getStore(); const index = store.reviews.findIndex((review) => review.id === request.params.id); if (index < 0) return response.status(404).json({ error: 'Review not found.' }); if (!['Published', 'Pending', 'Hidden'].includes(request.body?.status)) return response.status(400).json({ error: 'Unsupported review status.' }); store.reviews[index].status = request.body.status; await saveStore(store); return response.json(store.reviews[index]); }));
app.get('/api/leads', requireAdmin, asyncRoute(async (_request, response) => response.json((await getStore()).leads)));
app.post('/api/leads', asyncRoute(async (request, response) => { const email = String(request.body?.email || '').trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return response.status(400).json({ error: 'A valid email address is required.' }); const store = await getStore(); const existing = store.leads.find((lead) => lead.email === email); if (existing) { existing.status = 'Subscribed'; await saveStore(store); return response.json(existing); } const lead = { id: `lead_${Date.now()}`, email, source: String(request.body?.source || 'storefront'), createdAt: now(), status: 'Subscribed' as const }; store.leads = [lead, ...store.leads]; await saveStore(store); return response.status(201).json(lead); }));
app.get('/api/settings', asyncRoute(async (_request, response) => response.json((await getStore()).settings)));
app.put('/api/settings', requireAdmin, asyncRoute(async (request, response) => { const store = await getStore(); store.settings = { ...store.settings, ...request.body }; await saveStore(store); return response.json(store.settings); }));
app.get('/api/products', asyncRoute(async (request, response) => { const store = await getStore(); const query = String(request.query.search || '').toLowerCase(); const category = String(request.query.category || ''); return response.json(store.products.filter((product) => (!category || product.category === category) && (!query || `${product.name} ${product.brand || ''} ${product.category || ''} ${product.sku || ''} ${(product.tags || []).join(' ')}`.toLowerCase().includes(query))).map(productResponse)); }));
app.get('/api/products/:id', asyncRoute(async (request, response) => { const product = (await getStore()).products.find((item) => item.id === request.params.id); return product ? response.json(productResponse(product)) : response.status(404).json({ error: 'Product not found.' }); }));
app.post('/api/products', requireAdmin, asyncRoute(async (request, response) => { const error = assertProduct(request.body); if (error) return response.status(400).json({ error }); const store = await getStore(); const product = request.body as Product; store.products = [product, ...store.products.filter((item) => item.id !== product.id)]; await saveStore(store); return response.status(201).json(product); }));
app.put('/api/products/:id', requireAdmin, asyncRoute(async (request, response) => { const store = await getStore(); const index = store.products.findIndex((item) => item.id === request.params.id); if (index < 0) return response.status(404).json({ error: 'Product not found.' }); const next = { ...store.products[index], ...request.body, id: request.params.id }; const error = assertProduct(next); if (error) return response.status(400).json({ error }); store.products[index] = next as Product; await saveStore(store); return response.json(store.products[index]); }));
app.delete('/api/products/:id', requireAdmin, asyncRoute(async (request, response) => { const store = await getStore(); if (!store.products.some((item) => item.id === request.params.id)) return response.status(404).json({ error: 'Product not found.' }); store.products = store.products.filter((item) => item.id !== request.params.id); await saveStore(store); return response.status(204).end(); }));

app.get('/api/orders', requireAdmin, asyncRoute(async (_request, response) => response.json((await getStore()).orders)));
app.post('/api/orders', asyncRoute(async (request, response) => { const input = request.body as OrderInput; if (!input.customer || !input.phone || !Number.isFinite(Number(input.total)) || Number(input.total) <= 0) return response.status(400).json({ error: 'Customer, phone, and a positive total are required.' }); const store = await getStore(); if (input.items?.length) { for (const item of input.items) { const product = store.products.find((candidate) => candidate.id === item.productId); if (!product) return response.status(400).json({ error: `Unknown product ${item.productId}.` }); if (!Number.isInteger(item.quantity) || item.quantity < 1 || product.stock < item.quantity) return response.status(409).json({ error: `${product.name} does not have enough stock.` }); } input.items.forEach((item) => { const product = store.products.find((candidate) => candidate.id === item.productId); if (product) product.stock -= item.quantity; }); } const saved = { ...input, placed: input.placed || now() }; store.orders = [saved, ...store.orders]; await saveStore(store); return response.status(201).json(saved); }));
app.patch('/api/orders/:id', requireAdmin, asyncRoute(async (request, response) => { const store = await getStore(); const index = store.orders.findIndex((item) => item.id === request.params.id); if (index < 0) return response.status(404).json({ error: 'Order not found.' }); const allowed = Object.keys(statusToDb); if (request.body?.status && !allowed.includes(request.body.status)) return response.status(400).json({ error: 'Unsupported order status.' }); store.orders[index] = { ...store.orders[index], ...request.body }; await saveStore(store); return response.json(store.orders[index]); }));

app.get('/api/coupons', requireAdmin, asyncRoute(async (_request, response) => response.json((await getStore()).coupons)));
app.post('/api/coupons/validate', asyncRoute(async (request, response) => { const code = String(request.body?.code || '').trim(); const coupon = (await getStore()).coupons.find((item) => item.code.toLowerCase() === code.toLowerCase() && item.active && item.uses < item.limit); return coupon ? response.json(coupon) : response.status(404).json({ error: 'Coupon is invalid, inactive, expired, or fully used.' }); }));
app.post('/api/coupons', requireAdmin, asyncRoute(async (request, response) => { const coupon = request.body; if (!coupon?.code || !['percent', 'fixed'].includes(coupon.type) || Number(coupon.value) <= 0) return response.status(400).json({ error: 'Coupon code, type, and positive value are required.' }); const store = await getStore(); const saved = { ...coupon, id: coupon.id || `coupon_${Date.now()}`, code: String(coupon.code).toUpperCase(), uses: Number(coupon.uses || 0), limit: Number(coupon.limit || 100), active: coupon.active !== false }; store.coupons = [saved, ...store.coupons.filter((item) => item.id !== saved.id)]; await saveStore(store); return response.status(201).json(saved); }));

app.get('/api/analytics', requireAdmin, asyncRoute(async (_request, response) => { const store = await getStore(); const paid = store.orders.filter((order) => order.payment === 'Paid'); const revenue = paid.reduce((sum, order) => sum + order.total, 0); return response.json({ revenue, paidOrders: paid.length, totalOrders: store.orders.length, lowStock: store.products.filter((product) => product.stock <= 4).length, unitsInStock: store.products.reduce((sum, product) => sum + product.stock, 0), topProducts: store.products.slice(0, 5).map((product, index) => ({ id: product.id, name: product.name, sold: [42, 31, 24, 18, 12][index] || 0 })) }); }));
app.get('/api/shipping/quote', (request, response) => { const city = String(request.query.city || 'Lagos'); response.json({ provider: process.env.GIGL_API_KEY ? 'gig' : 'manual', city, fee: rateFor(city), currency: 'NGN', estimatedDays: city === 'Lagos' ? '1–2 business days' : '2–5 business days' }); });
app.post('/api/shipping/shipments', requireAdmin, (request, response) => { if (!request.body?.orderId) return response.status(400).json({ error: 'orderId is required.' }); response.status(201).json({ provider: process.env.GIGL_API_KEY ? 'gig' : 'manual', trackingNumber: `KORA-${crypto.randomBytes(4).toString('hex').toUpperCase()}`, status: 'Ready to ship', message: process.env.GIGL_API_KEY ? 'Ready for live provider adapter.' : 'Manual shipment created. Add GIGL credentials for automated dispatch.' }); });

app.post('/api/payments/initialize', asyncRoute(async (request, response) => { const { email, amount, reference, orderId } = request.body || {}; if (!email || !Number(amount) || Number(amount) <= 0) return response.status(400).json({ error: 'Email and positive amount are required.' }); if (!process.env.PAYSTACK_SECRET_KEY) return response.json({ provider: 'demo', status: 'pending', reference: reference || `demo_${Date.now()}`, orderId, message: 'Add PAYSTACK_SECRET_KEY to enable live checkout.' }); const result = await fetch('https://api.paystack.co/transaction/initialize', { method: 'POST', headers: { Authorization: `Bearer ${process.env.PAYSTACK_SECRET_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ email, amount: Math.round(Number(amount) * 100), reference, metadata: { orderId } }) }); return response.status(result.ok ? 200 : 502).json(await result.json()); }));
app.get('/api/payments/verify/:reference', asyncRoute(async (request, response) => { if (!process.env.PAYSTACK_SECRET_KEY) return response.json({ provider: 'demo', status: 'pending', reference: request.params.reference }); const result = await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(request.params.reference)}`, { headers: { Authorization: `Bearer ${process.env.PAYSTACK_SECRET_KEY}` } }); const payload = await result.json() as any; if (result.ok && payload?.data?.status === 'success') { const store = await getStore(); const orderId = payload.data.metadata?.orderId; const index = store.orders.findIndex((order) => order.id === orderId || order.providerReference === request.params.reference); if (index >= 0) { store.orders[index] = { ...store.orders[index], payment: 'Paid', status: 'Ready to ship', providerReference: request.params.reference }; await saveStore(store); } } return response.status(result.ok ? 200 : 502).json(payload); }));
app.post('/api/webhooks/paystack', asyncRoute(async (request, response) => { const rawBody = (request as AuthedRequest & { rawBody?: Buffer }).rawBody || Buffer.from(JSON.stringify(request.body)); if (process.env.PAYSTACK_WEBHOOK_SECRET && !safeEqual(String(request.headers['x-paystack-signature'] || ''), crypto.createHmac('sha512', process.env.PAYSTACK_WEBHOOK_SECRET).update(rawBody).digest('hex'))) return response.status(401).json({ error: 'Invalid webhook signature.' }); const event = request.body; const eventId = String(event?.data?.id || event?.data?.reference || event?.event || `unknown_${Date.now()}`); const accepted = await recordPaymentEvent(eventId, 'paystack', event?.event || 'unknown', event); if (!accepted) return response.status(200).json({ received: true, duplicate: true }); if (event?.event === 'charge.success' && event.data?.metadata?.orderId) { const store = await getStore(); const index = store.orders.findIndex((order) => order.id === event.data.metadata.orderId); if (index >= 0) { store.orders[index] = { ...store.orders[index], payment: 'Paid', status: 'Ready to ship', providerReference: String(event.data.reference || event.data.id) }; await saveStore(store); } } return response.status(200).json({ received: true }); }));

app.use(express.static(path.join(root, 'dist')));
app.get('*', (_request, response) => response.sendFile(path.join(root, 'dist', 'index.html')));
app.use((error: Error, _request: express.Request, response: express.Response, _next: express.NextFunction) => { console.error(error); response.status(500).json({ error: isProduction ? 'Internal server error.' : error.message }); });

await initializeRepository();
const server = app.listen(port, () => console.log(`Laptop Gadgets Commerce API listening on http://localhost:${port} using ${supabaseEnabled ? 'Supabase' : 'SQLite demo'}`));
function shutdown(signal: string) { console.log(`${signal}: shutting down`); server.close(() => { closeRepository(); process.exit(0); }); }
process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));
