export type MemoryMode = 'global' | 'project_only' | 'temporary_off' | 'off';
export type SpecialistRole = 'researcher' | 'visual_director' | 'artifact_maker' | 'connector_operator' | 'qa_reviewer' | 'synthesizer' | 'planner' | 'ux_strategist' | 'asset_producer';
export type MessageRole = 'user' | 'assistant' | 'system';
export type AgentMode = 'plan' | 'act';
export type MessageTurnType = 'plan' | 'tool_progress' | 'approval_required' | 'question_required' | 'question_answered' | 'blocked_run' | 'completion_summary' | 'message';
export interface AgentQuestionOption { id: string; label: string; description?: string; value: string; }
export interface AgentQuestion { id: string; header?: string; prompt: string; options?: AgentQuestionOption[]; allowMultiple?: boolean; allowCustomAnswer?: boolean; required?: boolean; status: 'pending' | 'answered' | 'dismissed'; answer?: string | string[]; answeredAt?: string; }
export interface AgentQuestionSet { id: string; header?: string; questions: AgentQuestion[]; status: 'pending' | 'answered' | 'dismissed'; submittedAt?: string; }

export interface Member { id: string; displayName: string; role: string; }
export interface UserProfile { id: string; displayName: string; email: string; avatarUrl?: string; locale?: string; timezone?: string; theme?: 'light' | 'dark' | 'system'; reducedMotion?: boolean; globalMemoryEnabled: boolean; defaultModel: string; [key: string]: any; }
export interface Project { id: string; name: string; description: string; status: string; instructions: string; memoryMode: MemoryMode; createdAt: string; updatedAt: string; allowedToolIds: string[]; members: Member[]; [key: string]: any; }
export interface Conversation { id: string; title: string; scope: 'project' | 'standalone'; projectId?: string; agentId?: string; memoryMode: MemoryMode; status: string; createdAt: string; updatedAt: string; [key: string]: any; }
export interface Attachment { id: string; name: string; size: number; mimeType: string; [key: string]: any; }
export interface Citation { title?: string; url?: string; snippet?: string; source?: string; [key: string]: any; }
export interface PlanStep { stepId: string; objective: string; assignedRole: SpecialistRole; dependsOn: string[]; candidateToolIds: string[]; risk: string; status: string; completionCriteria: string[]; [key: string]: any; }
export interface ToolApprovalRequest { id: string; tool?: string; title?: string; description?: string; risk?: string; status: 'pending' | 'approved' | 'rejected'; resolvedAt?: string; rejectionReason?: string; [key: string]: any; }
export interface ToolContinuationPacket { reqId: string; category: string; title: string; reason: string; suggestedConnectors?: Array<{ name: string; transport?: string; scopes?: string[] }>; manualUploadSpec?: Record<string, any>; approvedFallback?: string; resumeAction?: string; [key: string]: any; }
export interface AgentActivityEvent { id: string; runId: string; type: 'thought' | 'tool_call' | 'mcp_call' | 'context_read' | 'approval' | 'file' | 'subagent' | 'artifact' | 'status'; title: string; detail?: string; status: 'queued' | 'running' | 'completed' | 'waiting' | 'failed' | 'blocked'; timestamp: string; durationMs?: number; toolName?: string; connectorName?: string; scope?: string; safeInput?: Record<string, any>; safeOutput?: Record<string, any>; subagentTaskId?: string; }
export interface SubagentTask { taskId: string; parentRunId: string; role: SpecialistRole; goal: string; dependencies: string[]; status: 'queued' | 'running' | 'waiting' | 'completed' | 'failed' | 'blocked' | 'cancelled' | 'timed_out' | string; tokenBudget: number; tokensUsed: number; timeBudgetMs: number; inputPayload: Record<string, any>; outputPayload?: Record<string, any>; citations?: string[] | Citation[]; confidence: number; startedAt?: string; completedAt?: string; error?: string; activity?: AgentActivityEvent[]; [key: string]: any; }
export interface Message { id: string; conversationId: string; role: MessageRole; content: string; createdAt: string; turnType?: MessageTurnType; attachments?: Attachment[]; plan?: { goal: string; steps: PlanStep[]; delegationMode: string }; subagents?: SubagentTask[]; activity?: AgentActivityEvent[]; approvalRequest?: ToolApprovalRequest; question?: AgentQuestion; questions?: AgentQuestion[]; continuationPacket?: ToolContinuationPacket; citations?: Citation[]; artifactIds?: string[]; [key: string]: any; }
export interface ArtifactVersion { version: number; content: string; changeSummary: string; createdAt: string; [key: string]: any; }
export type ArtifactType = 'markdown' | 'diagram' | 'html_preview' | 'svg' | 'table' | 'image' | 'document' | string;
export interface Artifact { id: string; title: string; description: string; type: ArtifactType; currentVersion: number; projectId?: string; conversationId: string; status: string; createdAt: string; updatedAt: string; tags: string[]; versions: ArtifactVersion[]; [key: string]: any; }
export interface ProjectSource { id: string; name: string; projectId?: string; type: string; sizeBytes?: number; checksum?: string; extractionQuality?: string; extractedText?: string; tokenCount?: number; uploadedAt?: string; visibility?: string; [key: string]: any; }
export interface AgentDefinition { id: string; name: string; description: string; role?: 'main' | 'subagent' | 'both' | string; model?: string; purpose?: string; instructions?: string; allowedToolIds?: string[]; allowedSkillIds?: string[]; memoryPolicy?: MemoryMode; enabled: boolean; version?: string; [key: string]: any; }
export interface SkillDefinition { id: string; name: string; commandTrigger: string; description: string; instructions: string; requiredCapabilities?: string[]; allowedToolIds?: string[]; outputFormat?: string; risk?: string; version: string; enabled: boolean; author?: string; [key: string]: any; }
export interface RemoteMcpConnector { id: string; name?: string; displayName?: string; description?: string; endpoint?: string; url?: string; transport: string; status: string; authMode?: string; scopes?: string[]; tools?: string[]; health?: Record<string, any>; [key: string]: any; }
export interface ScheduledTask { id: string; name: string; prompt: string; schedule?: string; status: string; nextRunAt?: string; lastRunAt?: string; projectId?: string; agentId?: string; [key: string]: any; }
export interface MemoryItem { id: string; statement: string; category: string; scope: 'global' | 'project_only' | string; projectId?: string; sourceConversationId?: string; confidence: number; createdAt: string; reasonSaved: string; [key: string]: any; }
export interface AuditEvent { id: string; action: string; actor?: string; status?: string; createdAt?: string; timestamp?: string; metadata?: Record<string, any>; [key: string]: any; }
